#!/bin/sh

RELEASE=/var/www/wordpicker/

echo 'Copying Python files..'
cp -u *.py $RELEASE
echo 'Copying templates directory..'
cp -ru templates $RELEASE
echo 'Copying static directory..'
cp -ru static $RELEASE
